version: "3.9"

services:
  backend:
    build: ./backend
    container_name: backend
    working_dir: /app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/project_pys:/app
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend/react_pys
    container_name: frontend
    working_dir: /app
    volumes:
      - ./frontend/react_pys:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: npm run dev -- --host
